### ISSUE TITLE
 can you explain to me under what conditions the data tables of incoming, outgoing and will have data?

### ISSUE THREAD

**Issue by zengleyi** [moscajs/aedes-persistence-mongodb#47]
Excuse me, can you explain to me under what conditions the data tables of incoming, outgoing and will have data? I found that mine was always empty. Thank you very much！
The more detailed the better！

**Comment by robertsLando** [comment]
They are needed for QoS > 0 messages. If your is empty is just because there are no 'in flight' message left on them :) check aedes code:

https://github.com/moscajs/aedes/blob/master/lib/handlers/publish.js#L42

https://github.com/moscajs/aedes/blob/master/lib/handlers/pubrec.js#L18

https://github.com/moscajs/aedes/blob/master/lib/handlers/pubrel.js#L29

https://github.com/moscajs/aedes/blob/master/lib/handlers/pubrel.js#L47

https://github.com/moscajs/aedes/blob/master/lib/handlers/puback.js#L5
